/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
  const client = knex.context.client.config.client;

  return knex.schema.createTable('activity_logs', function (table) {
    table
      .uuid('id')
      .primary()
      .comment('Value must be auto-generated by the application');
    table.integer('user_id').unsigned().notNullable().comment('FK to users.id');
    table
      .bigInteger('device_id')
      .unsigned()
      .notNullable()
      .comment('FK to devices.id');
    table.text('activity').notNullable();
    table.string('ip_address', 25).notNullable().comment('Store ipv4 or ipv6');
    table.timestamp('timestamp').defaultTo(knex.fn.now());
    table.comment(
      'User actions will be logged here, updating of data is not allowed'
    );

    table
      .foreign('user_id', 'idx_activity_logs_user_id')
      .references('id')
      .inTable('users');
    table
      .foreign('device_id', 'idx_activity_logs_device_id')
      .references('id')
      .inTable('devices');

    if (client === 'mysql') {
      table.engine('InnoDB');
      table.charset('utf8mb4');
      table.collate('utf8mb4_general_ci');
    }
  });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
  return knex.schema.dropTable('activity_logs');
};
